{
 "title": "SLO: Kubernetes API",
 "tags": [
  "k8s",
  "api",
  "sla"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "api_percentile", "query": "50, 90, 99" },
   { "name": "availability_span", "query": "10m,1h,1d,7d,21d,30d,90d" },
   { "name": "verb_excl", "query": "CONNECT|WATCH|PROXY" }
  ]
 },
 "panels": [
  { "title": "Kube API", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Availability over $availability_span",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "format": "percentunit",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum_over_time(kubernetes::job:slo_kube_api_ok[$availability_span]) / sum_over_time(kubernetes::job:slo_kube_api_sample[$availability_span])\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "Budget remaining from $availability_span",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "scalar((sum_over_time(kubernetes::job:slo_kube_api_ok[$availability_span]) / sum_over_time(kubernetes::job:slo_kube_api_sample[$availability_span]) - 0.98999999999999999)) * (time() - max(timestamp(up{job=\"prometheus-k8s\"} offset $availability_span)))",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "SLO: Availaibility over 10m",
   "type": "graph",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(kubernetes::job:slo_kube_api_ok[10m]) / sum_over_time(kubernetes::job:slo_kube_api_sample[10m])\n",
     "legendFormat": "{{ job }}"
    }
   ]
  },
  {
   "title": "API non-200s/total ratio (except CONNECT|WATCH|PROXY)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (job, verb, code, instance)(kubernetes:job_verb_code_instance:apiserver_requests:ratio_rate5m{verb!~\"CONNECT|WATCH|PROXY\", code!~\"2..\"})",
     "legendFormat": "{{ verb }} - {{ code }} - {{ instance }}"
    }
   ]
  },
  {
   "title": "API requests ratios",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubernetes::job_verb_code:apiserver_requests:ratio_rate5m",
     "legendFormat": "{{ verb }} - {{ code }}"
    }
   ]
  },
  {
   "title": "API $api_percentile-th latency[ms] by verb (except CONNECT|WATCH|PROXY)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "kubernetes:job_verb_instance:apiserver_latency:pctl90rate5m{verb!~\"CONNECT|WATCH|PROXY\"}",
     "legendFormat": "{{ verb }} - {{ instance }}"
    }
   ]
  }
 ]
}